# Clippy configuration for SinkChart

# Allow multiple crate versions for specific packages that come from deep transitive dependencies
# We still want to catch version conflicts for direct and 1st/2nd level dependencies
allowed-duplicate-crates = [
    # System and platform dependencies (deep transitive, can't control)
    "linux-raw-sys",             # System interface - multiple versions from GTK ecosystem
    "rustix",                    # System calls - different versions in system libraries
    "windows_i686_gnullvm",      # Windows targets - from system dependencies
    "windows_aarch64_gnullvm",   # Windows ARM targets
    "windows_aarch64_msvc",      # Windows ARM MSVC
    "windows_i686_gnu",          # Windows x86 GNU
    "windows_i686_msvc",         # Windows x86 MSVC
    "windows_x86_64_gnu",        # Windows x64 GNU
    "windows_x86_64_gnullvm",    # Windows x64 GNU LLVM
    "windows_x86_64_msvc",       # Windows x64 MSVC
    "windows-sys",               # Windows system APIs
    "windows-targets",           # Windows target specifications
    
    # Core utilities with ecosystem version conflicts (deep transitive)
    "regex-automata",            # From tracing-subscriber vs newer regex
    "regex-syntax",              # From tracing-subscriber vs newer regex
    "rustc-hash",                # From Dioxus internals vs other UI libraries
    "hashbrown",                 # Core hash map - multiple versions in ecosystem
    "indexmap",                  # Ordered hash map - v1 vs v2 ecosystem split
    "bitflags",                  # Feature flags - v1 vs v2 ecosystem transition
    "syn",                       # Proc macro parsing - v1 vs v2 ecosystem transition
    "proc-macro-crate",          # Proc macro utilities - multiple versions
    
    # Serialization ecosystem (deep transitive)
    "toml_edit",                 # TOML parsing - multiple versions in tooling
    "schemars",                  # JSON schema - multiple versions in ecosystem
    "base64",                    # Base64 encoding - v0.21 vs v0.22
    
    # UI and graphics dependencies (deep transitive from Tauri/GTK)
    "raw-window-handle",         # Window handles - v0.5 vs v0.6 transition
    "phf",                       # Perfect hash functions - multiple versions
    "phf_shared",                # PHF shared utilities
    "phf_macros",                # PHF procedural macros
    "siphasher",                 # Hash function for PHF
    
    # Cross-platform and compatibility (deep transitive)
    "libloading",                # Dynamic library loading - v0.7 vs v0.8
    "convert_case",              # String case conversion
    "heck",                      # String case conversion (different crate)
    "winnow",                    # Parsing combinator - version conflicts
    
    # macOS specific dependencies (deep transitive)
    "core-foundation",           # macOS core foundation
    "objc2",                     # Objective-C bindings
    "objc2-foundation",          # Objective-C foundation
    "objc2-quartz-core",         # Objective-C Quartz
    "foreign-types",             # Foreign type wrappers
    "foreign-types-shared",      # Shared foreign types
    "block2",                    # Objective-C blocks
    "dispatch2",                 # Grand Central Dispatch
    
    # Error handling with version conflicts (we use thiserror v2, ecosystem uses v1)
    "thiserror",                 # Our choice: use v2, but ecosystem still on v1
    "thiserror-impl",            # Implementation details for thiserror
]