from_latest_tag = false
ignore_merge_commits = false
generate_mono_repository_global_tag = true
branch_whitelist = ["main", "master"]

[git_hooks.pre-commit]
script = """#!/bin/sh
set -e
mask fmt
mask lint
mask spellcheck
"""

[commit_types]
feat = { changelog_title = "Features", omit_from_changelog = false }
fix = { changelog_title = "Bug Fixes", omit_from_changelog = false }
docs = { changelog_title = "Documentation", omit_from_changelog = false }
style = { changelog_title = "Styling", omit_from_changelog = true }
refactor = { changelog_title = "Refactoring", omit_from_changelog = false }
perf = { changelog_title = "Performance", omit_from_changelog = false }
test = { changelog_title = "Testing", omit_from_changelog = true }
build = { changelog_title = "Build System", omit_from_changelog = false }
ci = { changelog_title = "Continuous Integration", omit_from_changelog = true }
chore = { changelog_title = "Miscellaneous", omit_from_changelog = true }
security = { changelog_title = "Security", omit_from_changelog = false }


[bump_profiles.default]
pre_bump_hooks = [
    "mask security",
    "mask test",
]
post_bump_hooks = [
    "git push",
    "git push origin {{ version }}",
]